name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
      actions: read
      
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 16.15.1

      - name: Instalação do Mocha para teste
        run: 
          cd src;
          npm install -g mocha;
          npm install

      - name: Execução do Teste
        run: mocha src/test/convert.js



    
